#!/usr/bin/env python3
"""
Setup script for MuniMetro credentials.

Supports two storage backends:
- Local: Saves to .env file for local development
- Google Cloud: Saves to Secret Manager for production deployment

Usage:
    python scripts/setup-credentials.py           # Local (.env file)
    python scripts/setup-credentials.py --cloud   # Google Cloud Secret Manager
"""

import argparse
import os
import sys
from getpass import getpass
from pathlib import Path

# Get project root
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
ENV_FILE = PROJECT_ROOT / ".env"

# GCP configuration
GCP_PROJECT_ID = os.getenv('GCP_PROJECT_ID', 'munimetro')

# Credentials to collect (name, prompt, is_secret)
CREDENTIALS = [
    ("BLUESKY_HANDLE", "Bluesky handle (e.g., munimetro.bsky.social)", False),
    ("BLUESKY_APP_PASSWORD", "Bluesky app password", True),
]


def load_existing_env():
    """Load existing .env file if it exists."""
    existing = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, _, value = line.partition('=')
                    existing[key.strip()] = value.strip()
    return existing


def save_env(values):
    """Save values to .env file."""
    lines = [
        "# MuniMetro credentials",
        "# Generated by scripts/setup-credentials.py",
        "# DO NOT commit this file to git",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={value}")

    with open(ENV_FILE, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def get_secret_from_gcp(secret_name):
    """Get a secret value from Google Cloud Secret Manager."""
    try:
        from google.cloud import secretmanager
        client = secretmanager.SecretManagerServiceClient()
        name = f"projects/{GCP_PROJECT_ID}/secrets/{secret_name}/versions/latest"
        response = client.access_secret_version(request={"name": name})
        return response.payload.data.decode("UTF-8")
    except Exception:
        return None


def save_secret_to_gcp(secret_name, secret_value):
    """Save a secret to Google Cloud Secret Manager."""
    from google.cloud import secretmanager

    client = secretmanager.SecretManagerServiceClient()
    parent = f"projects/{GCP_PROJECT_ID}"

    # Check if secret exists
    try:
        secret_path = f"{parent}/secrets/{secret_name}"
        client.get_secret(request={"name": secret_path})
        secret_exists = True
    except Exception:
        secret_exists = False

    # Create secret if it doesn't exist
    if not secret_exists:
        client.create_secret(
            request={
                "parent": parent,
                "secret_id": secret_name,
                "secret": {"replication": {"automatic": {}}},
            }
        )

    # Add new version with the secret value
    secret_path = f"{parent}/secrets/{secret_name}"
    client.add_secret_version(
        request={
            "parent": secret_path,
            "payload": {"data": secret_value.encode("UTF-8")},
        }
    )


def prompt_for_credentials(existing=None):
    """Prompt user for credentials, showing masked existing values."""
    if existing is None:
        existing = {}

    values = {}
    for key, prompt, is_secret in CREDENTIALS:
        existing_value = existing.get(key)

        if existing_value:
            masked = existing_value[:3] + "***" if len(existing_value) > 3 else "***"
            display_prompt = f"{prompt} [{masked}]: "
        else:
            display_prompt = f"{prompt}: "

        if is_secret:
            new_value = getpass(display_prompt)
        else:
            new_value = input(display_prompt)

        # Use new value if provided, otherwise keep existing
        if new_value:
            values[key] = new_value
        elif existing_value:
            values[key] = existing_value
        else:
            print(f"  Warning: {key} not set")

    return values


def setup_local():
    """Setup credentials for local development."""
    print("=" * 50)
    print("MuniMetro Credential Setup (Local)")
    print("=" * 50)
    print()
    print(f"This will save credentials to: {ENV_FILE}")
    print("(This file is gitignored and safe to store locally)")
    print()

    # Load existing values
    existing = load_existing_env()
    if existing:
        print(f"Found existing .env with {len(existing)} value(s).")
        print("Press Enter to keep existing values, or type new value to replace.")
        print()

    values = prompt_for_credentials(existing)

    if not values:
        print("No credentials to save.")
        return

    save_env(values)
    print()
    print(f"Saved {len(values)} credential(s) to {ENV_FILE}")
    print()
    print("Credentials will be loaded automatically when running locally.")
    print()


def setup_cloud():
    """Setup credentials in Google Cloud Secret Manager."""
    print("=" * 50)
    print("MuniMetro Credential Setup (Google Cloud)")
    print("=" * 50)
    print()
    print(f"Project: {GCP_PROJECT_ID}")
    print("This will save credentials to Google Cloud Secret Manager.")
    print()

    # Check for google-cloud-secret-manager
    try:
        from google.cloud import secretmanager
    except ImportError:
        print("Error: google-cloud-secret-manager not installed.")
        print("Run: pip install google-cloud-secret-manager")
        sys.exit(1)

    # Load existing values from Secret Manager
    existing = {}
    print("Checking for existing secrets...")
    for key, _, _ in CREDENTIALS:
        value = get_secret_from_gcp(key)
        if value:
            existing[key] = value
            print(f"  Found: {key}")

    if existing:
        print()
        print("Press Enter to keep existing values, or type new value to replace.")

    print()
    values = prompt_for_credentials(existing)

    if not values:
        print("No credentials to save.")
        return

    # Save to Secret Manager
    print()
    print("Saving to Secret Manager...")
    for key, value in values.items():
        save_secret_to_gcp(key, value)
        print(f"  Saved: {key}")

    print()
    print(f"Saved {len(values)} credential(s) to Secret Manager.")
    print()
    print("To use in Cloud Run, deploy with:")
    print("  ./deploy/cloud/deploy-services.sh")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Setup MuniMetro credentials for local or cloud environments."
    )
    parser.add_argument(
        "--cloud",
        action="store_true",
        help="Store credentials in Google Cloud Secret Manager instead of local .env file",
    )
    args = parser.parse_args()

    if args.cloud:
        setup_cloud()
    else:
        setup_local()


if __name__ == "__main__":
    main()
